platform :ios, '6.0'
workspace 'JTLocalizeExample.xcworkspace'
xcodeproj 'JTLocalizeExample.xcodeproj'

inhibit_all_warnings!

pod 'DTCoreText'
pod 'JTLocalize', :git => 'https://github.com/joytunes/JTLocalize.git'
